name: Build and Deploy to GitHub Pages with Custom Path

on:
  push:
    branches:
      - main

permissions:  # 增加权限配置
  contents: write
  pages: write
  id-token: write  # 关键权限，确保拥有 id-token

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site/DecisionTable  # 指定将网站内容构建到 /DecisionTable 子目录中
          verbose: true

      - name: Ensure _site directory exists
        run: | 
          mkdir -p ./_site  # 创建 _site 目录（如果它不存在）
          sudo chmod -R 777 ./_site  # 强制为 _site 目录设置写权限
        
      - name: Create CNAME file for custom domain
        run: echo 'example.site' > ./_site/CNAME  # CNAME 文件只能包含域名

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          name: github-pages
          retention-days: 1

  report-build-status:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Report build status
        run: |
          gh api -X POST "repos/$GITHUB_REPOSITORY/pages/telemetry" \
            -F github_run_id="$GITHUB_RUN_ID" \
            -F conclusion="success"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONCLUSION: success

  deploy:
    needs: [build, report-build-status]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
